### ISSUE TITLE
USB-C capture device support?

### ISSUE THREAD

**Issue by reedog117** [eerimoq/moblin#11]
Would like to be able to use USB-C capture devices like the j5 create with USB C PD pass through for connecting iPhone 15 Pro to external cameras with HDMI output.

**Comment by XGxF3** [comment]
I'm not sure what you are asking for. Looks like the e j5 create is a HDMI adaptor if it was a usb-c adaptor you could connect your iPhone 15 to a tv or monitor. That can already be done. It is part of iOS.

**Comment by reedog117** [comment]
No. I'm talking about the jva02 or jva11 which are USB-C HDMI capture
devices similar to Elgato Camlink.

Linking to a workshop from WWDC23 where external USB-C devices are accessed
from iPadOS, but I bet the exact same libraries are available for use on
iPhone 15 Pro with USB-C and UVC-compliant USB HDMI capture devices.

https://developer.apple.com/videos/play/wwdc2023/10106/

**Comment by XGxF3** [comment]
This has been looked into. iOS does not have UVC support like iPadOS. Until Apple changes that there is nothing he can do.

**Comment by reedog117** [comment]
Reopening this as Moblin does run on iPadOS and there are significant potential cost savings running with an external camera on this setup. 

I’m currently running Moblin on a 3rd gen iPad Pro 11-inch with an M1 processor. The audio device on a USB-C UVC video capture device is already recognized without issue. I’m guessing it shouldn’t be much work to add the additional video source as another camera in the list.

**Comment by eerimoq** [comment]
Select the USB camera as camera in a scene and it works for most cameras.
