### ISSUE TITLE
 Unable to support SRT Access Control (Stream ID) Guidelines URL

### ISSUE THREAD

**Issue by tentenlee100** [eerimoq/moblin#15]
I am using SRS as the host for SRT, but the issue I'm encountering is that it cannot send out using the streamId method. When receiving on the server side, no streamId is received. SRS claims to use the SRT Access Control specifications.

srs server srt doc [here](https://ossrs.io/lts/en-us/docs/v5/doc/srt#srt-url)

[SRT Access Control (Stream ID) Guidelines](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md)

**Comment by eerimoq** [comment]
You can. Either you enter the stream id in the stream setup wizard, or you can manually percent encode the stream id and enter it in Settings -> Streams -> My stream -> URL

**Comment by a29726479** [comment]
Sponsored $10 without BELABOX Cloud SRT + srtla Relay Server
