### ISSUE TITLE
Disconnects after being in the background

### ISSUE THREAD

**Issue by rubaz100** [eerimoq/moblin#2]
Could you add a feature to stream with the screen turned off? It should save a lot energy.

And is it compatible with Bluetooth and wired mic compatiblen

**Comment by eerimoq** [comment]
Apple does not allow streaming in background, so it will disconnect. Not much to do about it. Screen does not use as much power as you think. Networking and widgets use way more. That said, I think iOS has some feature built in to make screen black/off. Not sure how. Someone in Discord knows.

From Xcode:

<img width="1032" alt="image" src="https://github.com/eerimoq/moblin/assets/176810/a1f2f80f-933a-4d4c-90c5-9a597f1f2dec">


I've only tested Bluetooth mic, but I think wired works as well.

**Comment by eerimoq** [comment]
Yes and Will be automatically selected. If not, it is a bug.
