### ISSUE TITLE
FPS for Browser is to low

### ISSUE THREAD

**Issue by rene-mueller** [eerimoq/moblin#24]
Is it possible to increase the bit rate to at least 30 FPS?

best regards,
René

**Comment by eerimoq** [comment]
Browser widgets are very inefficient. High FPS will likely make your phone overheat very quickly. But haven't tested.

Would be awesome if you can clone and build Moblin with a higher limit and evaluate it.

**Comment by rene-mueller** [comment]
@eerimoq I would like to do this, but I no longer have apple developer access.

**Comment by eerimoq** [comment]
You can test without apple developer access. See: https://github.com/eerimoq/moblin?tab=readme-ov-file#development-environment-setup
