### ISSUE TITLE
Potential scenarios where you could unintentionally share your location to rtirl

### ISSUE THREAD

**Issue by juaoose** [eerimoq/moblin#28]
Hello! I believe there are some potential scenarios where a user could leak their location on rtirl by mistake:

When one starts a stream with rtirl and location enabled and then perform one or many of the actions listed below, the `/stop` endpoint of rtirl is not called, and as such you potentially still appear in the public map.
- Disable location.
- Disable rtirl.
- Add a privacy zone that overlaps with the current location?

Calling stop in these scenarios would help the streamer not have to stop streaming and be able to not show in rtirl map. (Maybe for the privazy zone case there could be other alternatives...)
Thanks!

**Comment by eerimoq** [comment]
Will have a look at it.

**Comment by eerimoq** [comment]
Should be fixed in 0.273.0. Thanks for reporting.

**Comment by juaoose** [comment]
> Should be fixed in 0.273.0. Thanks for reporting.
> 
> Let me know if it works as expected once the fix is available in TestFlight.

Yeah, that seems to work! Thanks for the help!
