### ISSUE TITLE
Include IPA with releases?

### ISSUE THREAD

**Issue by therysin** [eerimoq/moblin#52]
Hi, thank for creating this app, its possibly the best streaming application available for iOS.

Would it be possible to include an IPA with your future releases on github for those who would like to sideload? Thank you.

**Comment by eerimoq** [comment]
Do you know how to do it?

**Comment by therysin** [comment]
I'm not sure, not being an apple developer, but the links below should help:

https://github.com/MrKai77/Export-unsigned-ipa-files
https://forums.developer.apple.com/forums/thread/109122

**Comment by eerimoq** [comment]
Will postpone this.

**Comment by therysin** [comment]
I made a script that does this very easily. Simply place the script in the project directory and run it.

https://github.com/therysin/UnsignedIPAGen
