### ISSUE TITLE
Support for UVC on iPhone

### ISSUE THREAD

**Issue by fdebbabi** [eerimoq/moblin#67]
According to the documentation (the README.md) the app supports UVC (USB-C) cameras on iPad.
Does it support also UVC (USB-C) on iPhones with USB C?(iPhone 15, 15 Pro, ..).

Is there an Android version/Do you happen to know an alternative to Moblin with UVC support and Network Bonding on Android? 

Thank you for the amazing app :)

**Comment by eerimoq** [comment]
iPhone do not support USB cameras. Apple limitation. At least that's what I've heard.

The Android app IRL Pro has bonding.

**Comment by fdebbabi** [comment]
Thank you, that answers my question.
