### ISSUE TITLE
Apply css stylesheet to the bowser widget

### ISSUE THREAD

**Issue by janis-lv** [eerimoq/moblin#69]
Would be nice if we can apply custom css stylesheet to the browser widget.

Thank you very much for this great application!

Jānis

**Comment by eerimoq** [comment]
Feel free to suggest UI and examples

**Comment by janis-lv** [comment]
UI (copied from Larix Broadcaster):
[cid:2f07707f-b719-4923-8204-2bdff3e5b9f9]



For example, we can apply this css to extract tournament table from web page.
URL:
https://www.floorball.lv/lv/2023/jaunatne/zu14/tabula
CSS:
body {
    visibility: hidden;
  width: auto !important;
  background: none;
  font-family: 'Calibri', sans-serif;
  font-size: 24px
  }
#header{height: 0px; width:0px;}
.colmask{position: absolute;}
.colmid{margin-left: 0px!important;}
.colleft{left:0%!important; }
.col3{width: 0px!important; left: 0%!important;}
  #chempionats_tabula_34 {
    visibility: visible;
    position: absolute;
    left: 0;
    top: 0;
  }
#chempionats_tabula_34[style]{width: 100%!important;}
table.tabula td {line-height: 30px}
table.tabula th {background: rgba(19, 69, 85, 0.5);}



Thanks!
Jānis




________________________________

**Comment by janis-lv** [comment]
UI (copied from Larix Broadcaster):
![image](https://github.com/user-attachments/assets/a491319d-4a98-4190-8eeb-cb10309d2a35)

For example, we can apply this css to extract tournament table from web page.
URL:
https://www.floorball.lv/lv/2023/jaunatne/zu14/tabula
CSS:
body {
    visibility: hidden;
  width: auto !important;
  background: none;
  font-family: 'Calibri', sans-serif;
  font-size: 24px
  }
#header{height: 0px; width:0px;}
.colmask{position: absolute;}
.colmid{margin-left: 0px!important;}
.colleft{left:0%!important; }
.col3{width: 0px!important; left: 0%!important;}
  #chempionats_tabula_34 {
    visibility: visible;
    position: absolute;
    left: 0;
    top: 0;
  }
#chempionats_tabula_34[style]{width: 100%!important;}
table.tabula td {line-height: 30px}
table.tabula th {background: rgba(19, 69, 85, 0.5);}

**Comment by eerimoq** [comment]
In Test Flight (beta testing) now. See README for how to use Test Flight.

Paste your style sheet (CSS) in Settings -> Scenes -> My widget -> Style sheet

**Comment by janis-lv** [comment]
Made a test stream. Working perfectly. UI is clean and fits my need ideally.
You are the best :)
