### ISSUE TITLE
iPad sometime starts in portrait mode

### ISSUE THREAD

**Issue by XGxF3** [eerimoq/moblin#7]
iPad in landscape orientation

Moblin not running

On a fresh launch Moblin always shows up in portrait view. Then rotates to landscape. In a few occasions it stays in portrait and requires restarting app or physically rotating the iPad to fix.

**Comment by eerimoq** [comment]
Fixed in 0.178.0?

**Comment by XGxF3** [comment]
Yes .178 has fixed the issue
